"""
AbstractStrategy — base class for all trading strategies.

Every strategy implements generate_signals() which is called by the
trading engine on each tick. The engine then:
1. Passes signals through Kelly/DEPO position sizing
2. Applies risk checks (position limits, circuit breakers)
3. Places orders via IBroker

Strategies must NOT:
  - Call IBroker directly
  - Store mutable state between ticks that would cause data leakage in backtests
  - Use any information not available at the signal generation timestamp

Strategies SHOULD:
  - Be stateless or have state that can be reset via reset()
  - Implement fit() if they have parameters to estimate from historical data
  - Return empty list if no edge is found (never force a trade)
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

from app.schemas.market import MarketOut


def _now() -> datetime:
    return datetime.now(timezone.utc)


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.

    The trading engine consumes this and decides whether to act
    based on Kelly fraction, risk limits, and current portfolio.
    """
    ticker: str
    direction: str              # "buy_yes" | "buy_no" | "sell_yes" | "sell_no"
    fair_value: float           # Strategy's estimated true probability of YES (0-1)
    market_price: float         # Current market price for the side being traded (0-1)
    edge: float                 # fair_value - market_price for YES trades (signed)
    confidence: float           # 0-1 confidence in the signal
    strategy_name: str
    metadata: dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=_now)

    @property
    def edge_bps(self) -> float:
        """Edge in basis points."""
        return self.edge * 10_000

    @property
    def is_long_yes(self) -> bool:
        return self.direction == "buy_yes"

    @property
    def is_long_no(self) -> bool:
        return self.direction == "buy_no"


class AbstractStrategy(ABC):
    """Base class for all trading strategies."""

    name: str = "abstract"
    display_name: str = "Abstract Strategy"
    description: str = ""

    DEFAULT_PARAMS: dict[str, Any] = {}

    def __init__(self, params: Optional[dict[str, Any]] = None) -> None:
        self.params = {**self.DEFAULT_PARAMS, **(params or {})}
        self.enabled = False

    @abstractmethod
    def generate_signals(
        self,
        markets: list[MarketOut],
        portfolio_equity: float,
    ) -> list[Signal]:
        """
        Generate trading signals for the given market snapshots.

        Args:
            markets: Current market snapshots (only use data up to now)
            portfolio_equity: Current total portfolio equity for sizing

        Returns:
            List of signals (empty if no edge found)
        """
        ...

    def fit(self, historical_markets: list[MarketOut]) -> None:
        """
        Optional: fit strategy parameters on historical data.
        Called by backtest engine before each test fold.
        Default: no-op.
        """
        pass

    def reset(self) -> None:
        """
        Reset strategy state between backtest folds.
        Default: no-op (stateless strategies don't need this).
        """
        pass

    def get_params(self) -> dict[str, Any]:
        return dict(self.params)

    def set_params(self, params: dict[str, Any]) -> None:
        self.params.update(params)
